name: debouncing_example
description: "Demonstrates how to use the debouncing package"

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  collection: ^1.18.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  provider: ^6.1.4
  meta: ^1.15.0
  debouncing:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.0.2


flutter:
  uses-material-design: true

