name: debouncing
description: "A lightweight Flutter package providing a simple [debounce, throttle, back off] utility to function calls, ideal for optimizing performance in event-driven application."
version: 1.0.1
homepage: https://github.com/javlon92/debouncing
repository: https://github.com/javlon92/debouncing
issue_tracker: https://github.com/javlon92/debouncing/issues

topics: [throttling, debouncing, throttle, debounce, backoff]

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
